name: futureama_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  fluttertoast: ^8.2.1
  provider: ^6.0.5
  flutter_switch: ^0.3.2
  shared_preferences: ^2.1.0
  shimmer: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter: # Flutter Version: 3.7.12

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: poppins_regular
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
